SELECT * FROM
(
SELECT
ACUNIT.ACCOUNTUNIT AS BRANCH
, BPB.BILL_NO AS BILLNO
, DATE(BPB.BILL_DATE) AS BILLDATE
, DATE(BPB.REVENUE_DATE) AS REVENUEDATE
, PAT.PATIENTID AS MRN
, RDP.PAYORTYP AS PAYOR
, BPB.BILL_AMOUNT AS BILLAMOUNT
, BPB.DISCOUNT_AMOUNT AS DISCOUNT
, (BPB.BILL_AMOUNT) - (BPB.DISCOUNT_AMOUNT) AS NETAMOUNT
, BPB.PAID_AMOUNT AS PAIDAMOUNT
, BPB.CLAIM_AMOUNT AS BILLCLAIMAMOUNT
, (SUM(DETAIL.CLAIM_AMOUNT)) AS SERVICECLAIMAMOUNT
,DIRECTSALES.`TOTALCLAIMAMOUNT` AS SALESCLAIMAMOUNT
, (SUM(DIRECTSALESDETAIL.CLAIMAMOUNT)) AS SALESDETAILCLAIMAMOUNT
,CASE WHEN DIRECTSALES.ID IS NULL THEN 'SERVICE BILL'
ELSE 'SALESBILL'
END AS TYPE
FROM
RT_DATA_ACCOUNT_UNIT ACUNIT
JOIN BILL_PATIENT_BILL BPB ON BPB.ACC_UNIT_ID = ACUNIT.ID
JOIN BILL_SERVICE_DETAIL AS DETAIL ON DETAIL.BILL_ID = BPB.ID
 AND
(
SERVICE_ID IS NULL OR SERVICE_ID NOT LIKE 'PKG%'
AND BILL_STATUS <> 4
)
JOIN RT_INDIVIDUAL_PATIENT PAT ON BPB.PATIENT_ID=PAT.ID
JOIN RT_DATA_PAYORTYPE RDP ON RDP.ID=BPB.PAYOR_TYPE_ID
LEFT JOIN RT_TICKET_DIRECTSALES AS DIRECTSALES ON DIRECTSALES.ID = DETAIL.SERVICE_ID
LEFT JOIN RT_TICKET_DIRECTSALESDETAIL AS DIRECTSALESDETAIL ON DIRECTSALESDETAIL.SALESID = DIRECTSALES.ID
WHERE

DATE(BPB.BILL_DATE) =DATE_SUB(CURDATE(), INTERVAL 1 DAY)
AND BPB.BILL_AMOUNT > 0
AND RDP.PAYORCATEGORY NOT IN ('CASH')
GROUP BY
ACUNIT.ACCOUNTUNIT
, BPB.BILL_NO
ORDER BY
ACUNIT.ACCOUNTUNIT
) AS A
WHERE
(
(TYPE ='SERVICE BILL' AND (A.BILLCLAIMAMOUNT - A.SERVICECLAIMAMOUNT) > 2) OR (TYPE='SALESBILL' AND (A.SALESCLAIMAMOUNT - A.SALESDETAILCLAIMAMOUNT) > 2)
OR (TYPE ='SERVICE BILL' AND (A.BILLCLAIMAMOUNT - A.SERVICECLAIMAMOUNT) < -2) OR (TYPE='SALESBILL' AND (A.SALESCLAIMAMOUNT - A.SALESDETAILCLAIMAMOUNT) < -2)

)
