SELECT * FROM
(
SELECT
IF(ITM.ITEMCODE IS NULL,'',ITM.ITEMCODE) AS 'item_code',
IF(ITM.ADITMNAME IS NULL,SDTL.ITEMNAME,ITM.ADITMNAME) AS 'item_name',
ITM.ADITMUNIT AS 'uom',
IF(PAT.PATIENTID IS NULL,'Retail Sales',SDTL.SALESDETAILSTATUS) AS 'trans_type',
DATE(BILL.BILL_DATE) AS 'trans_date',
IF(ITM.ITEMTYPE = 'F','Frames',IF(ITM.ITEMTYPE = 'L','Lens',IF(ITM.ITEMTYPE = 'M','Material',IF(ITM.ITEMTYPE = 'D','Drugs','Lens')))) AS 'item_type',
CASE
      WHEN ITMC.ITMCGCATEGNAME IN ('FRAMES','LENS','CONTACT LENS','SUNGLASS','OPTICAL LENS') THEN 'OPTICALS'

      WHEN ITMC.ITMCGCATEGNAME LIKE  ('%OPTICAL SUNGLASS%') THEN 'OPTICALS'
      WHEN ITMC.ITMCGCATEGNAME LIKE  ('%FRAME%') THEN 'OPTICALS'
    WHEN ITMC.ITMCGCATEGNAME LIKE '%PHARMACY%' THEN 'PHARMACY'
    WHEN ITMC.ITMCGCATEGNAME LIKE '%LAB%' THEN 'LABORATORY'
      WHEN ITMC.ITMCGCATEGNAME LIKE '%OPERATION THEAT%' THEN 'OPERATION THEATRE'
--     ELSE  'OPERATION THEATRE'
    END AS 'top',
-- IF(ITM.ITEMTYPE = 'F','Opticals',(IF(ITM.ITEMTYPE = 'D','Pharmacy',IF(ITM.ITEMTYPE = 'M','Surgery & Others','Opticals')))) AS 'top',
-- IF(ITM.ITEMTYPE = 'F','Opticals',(IF(ITM.ITEMTYPE = 'D','Pharmacy',IF(ITM.ITEMTYPE = 'M','Surgery','Opticals')))) AS 'second',
ITM.ADITMDEPT AS 'second',
ITMC.ITMCGCATEGNAME AS 'group',
ITM.SUBCATEGORY AS 'sub_group',
BILL.BILL_NO AS 'bill_no',
(SDTL.QUANTITY) AS 'quantity',
IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) AS 'unit_price',
IF(SSD.COST_PRICE IS NULL ,IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.COST_PRICE) AS 'cost_price',
(IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) * (SDTL.QUANTITY)) AS 'actual_value',
RDT.TAX AS 'tax',
RDT.VALUE AS 'tax_percent',
UNIT.ACCOUNTUNIT AS 'branch',
ROC.DESCRIPTION AS 'entity',
IF(ITMC.ITMCGCATEGNAME = 'LENS','OPTICAL LENS',DEPT.DEPARTMENTNAME) AS 'unit',
SALES.WORKORDERSTATUS AS 'wo_status',
IF(MANF.ID IS NULL,ITM.MANUFACTURERID,MANF.MANUFACTURER) AS MANUFACTURER
FROM
RT_DATA_ACCOUNT_UNIT UNIT
JOIN BILL_PATIENT_BILL BILL ON BILL.ACC_UNIT_ID = UNIT.ID
JOIN RT_DATA_CORE RDC ON RDC.ID=UNIT.ID
JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=RDC.TENANTID
JOIN BILL_SERVICE_DETAIL DTL ON BILL.ID = DTL.BILL_ID
JOIN RT_TICKET_DIRECTSALES SALES ON DTL.SERVICE_ID = SALES.ID
JOIN RT_TICKET_DIRECTSALESDETAIL SDTL ON SALES.ID = SDTL.SALESID
JOIN RT_DATA_ITEM ITM ON ITM.ID = SDTL.ITEMID LEFT JOIN  RT_ORGANIZATION_MANUFACTURER MANF ON MANF.ID = ITM.MANUFACTURERID
LEFT JOIN RT_DATA_TAX RDT ON RDT.ID=ITM.TAXTYPE
LEFT JOIN RT_INDIVIDUAL_PATIENT AS PAT ON(BILL.PATIENT_ID = PAT.ID)
JOIN RT_DATA_ITEM_CATEGORY ITMC ON ITM.CATEGORY = ITMC.ID
LEFT JOIN STORE_STOCK_DETAIL AS SSD ON (SDTL.STOCKDETAILID = SSD.ID)
LEFT JOIN RT_DATA_DEPARTMENT AS DEPT ON (SDTL.DEPTID = DEPT.ID)
WHERE
-- BILL.BILL_DATE BETWEEN concat(curdate(),' ','00:00:00') and concat(curdate(),' ','23:59:59')
DATE(BILL.BILL_DATE)=DATE_SUB(CURDATE(), INTERVAL 1 DAY)
-- BETWEEN  '2018-04-01 00:00:00' AND '2019-05-15 23:59:59'
AND DTL.SERVICE_ID IS NOT NULL
-- AND (SALES.WORKORDERSTATUS = 'Goods Delivered' OR SALES.WORKORDERSTATUS IS NULL)
AND BILL.BILL_AMOUNT<>0
AND UNIT.ACCOUNTUNIT NOT IN ('ERC', 'OHC')
AND UNIT.DATASTATUS='Active'
-- AND ITM.ITEMTYPE<>'L'
-- and UNIT.ACCOUNTUNIT ='CMH'
UNION ALL
SELECT
ITM.ITEMCODE AS 'item_code',
ITM.ADITMNAME AS 'item-name',
ITM.ADITMUNIT AS 'uom',
SADTL.REASON AS 'trans_type',
DATE(CRE.CREATEDTIME) AS 'trans_date',
IF(ITM.ITEMTYPE = 'F','Frames',IF(ITM.ITEMTYPE = 'L','Lens',IF(ITM.ITEMTYPE = 'M','Material',IF(ITM.ITEMTYPE = 'D','Drugs','Lens')))) AS 'item_type',
-- IF(ITM.ITEMTYPE = 'F','Opticals',(IF(ITM.ITEMTYPE = 'D','Pharmacy',IF(ITM.ITEMTYPE = 'M','Surgery & Others','Opticals')))) AS 'top',
CASE
      WHEN ITMC.ITMCGCATEGNAME IN ('FRAMES','LENS','CONTACT LENS','SUNGLASS','OPTICAL LENS') THEN 'OPTICALS'

      WHEN ITMC.ITMCGCATEGNAME LIKE  ('%OPTICAL SUNGLASS%') THEN 'OPTICALS'
      WHEN ITMC.ITMCGCATEGNAME LIKE  ('%FRAME%') THEN 'OPTICALS'
    WHEN ITMC.ITMCGCATEGNAME LIKE '%PHARMACY%' THEN 'PHARMACY'
    WHEN ITMC.ITMCGCATEGNAME LIKE '%LAB%' THEN 'LABORATORY'
      WHEN ITMC.ITMCGCATEGNAME LIKE '%OPERATION THEAT%' THEN 'OPERATION THEATRE'
    END AS 'top',
-- IF(ITM.ITEMTYPE = 'F','Opticals',(IF(ITM.ITEMTYPE = 'D','Pharmacy',IF(ITM.ITEMTYPE = 'M','Surgery','Opticals')))) AS 'second',
ITM.ADITMDEPT AS 'second',
ITM.SUBCATEGORY AS 'group',
ITM.SUBCATEGORY AS 'sub_group',
SADTL.ID AS 'bill_no',
SADTL.QUANTITY AS 'quantity',
SSDTL.UNIT_PRICE AS 'unit_price',
SSDTL.COST_PRICE AS 'cost_price',
IF(SSDTL.COST_PRICE IS NULL ,SSDTL.UNIT_PRICE,SSDTL.COST_PRICE)*SADTL.QUANTITY AS 'actual_value',
RDT.TAX AS 'tax',
RDT.VALUE AS 'tax_percent',
UNIT.ACCOUNTUNIT AS 'branch',
ROC.DESCRIPTION AS 'entity',
DEP.DEPARTMENTNAME AS 'unit',
'' AS 'wo_status',
IF(MANF.ID IS NULL,ITM.MANUFACTURERID,MANF.MANUFACTURER) AS MANUFACTURER
FROM
RT_TICKET_STOCKADJUSTMENTDETAIL SADTL
JOIN RT_TICKET_CORE CRE ON SADTL.ID = CRE.ID
JOIN RT_DATA_ITEM ITM ON ITM.ID = SADTL.ITEMID LEFT JOIN  RT_ORGANIZATION_MANUFACTURER MANF ON MANF.ID = ITM.MANUFACTURERID
JOIN RT_DATA_ITEM_CATEGORY ITMC ON ITM.CATEGORY = ITMC.ID
LEFT JOIN RT_DATA_TAX RDT ON RDT.ID=ITM.TAXTYPE
JOIN STORE_STOCK_DETAIL SSDTL ON SADTL.STOCKDETAILID = SSDTL.ID
JOIN RT_DATA_DEPARTMENT DEP ON SADTL.DEPTID = DEP.ID
JOIN RT_DATA_ACCOUNT_UNIT UNIT ON DEP.ACCOUNTUNITID = UNIT.ID
JOIN RT_DATA_CORE RDC ON RDC.ID=UNIT.ID
JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=RDC.TENANTID
WHERE DATE(CRE.CREATEDTIME)=DATE_SUB(CURDATE(), INTERVAL 1 DAY)
-- BETWEEN  '2018-04-01 00:00:00' AND '2019-05-15 23:59:59'
-- AND SADTL.REASON LIKE 'Item Consumed'
AND TRANSTYPE LIKE 'Reduction'
AND UNIT.ACCOUNTUNIT NOT IN ('ERC', 'OHC')
AND UNIT.DATASTATUS='Active'
-- AND UNIT.ACCOUNTUNIT ='CMH'
UNION ALL
SELECT
IF(ITM.ITEMCODE IS NULL,'',ITM.ITEMCODE) AS 'item_code',
IF(ITM.ADITMNAME IS NULL,SDTL.ITEMNAME,ITM.ADITMNAME) AS 'item_name',
ITM.ADITMUNIT AS 'uom',
IF(PAT.PATIENTID IS NULL,'Retail Sales',SDTL.SALESDETAILSTATUS) AS 'trans_type',
DATE(RETCORE.CREATEDTIME) AS 'trans_date',
IF(ITM.ITEMTYPE = 'F','Frames',IF(ITM.ITEMTYPE = 'L','Lens',IF(ITM.ITEMTYPE = 'M','Material',IF(ITM.ITEMTYPE = 'D','Drugs','Lens')))) AS 'item_type',
CASE
      WHEN ITMC.ITMCGCATEGNAME IN ('FRAMES','LENS','CONTACT LENS','SUNGLASS','OPTICAL LENS') THEN 'OPTICALS'

      WHEN ITMC.ITMCGCATEGNAME LIKE  ('%OPTICAL SUNGLASS%') THEN 'OPTICALS'
      WHEN ITMC.ITMCGCATEGNAME LIKE  ('%FRAME%') THEN 'OPTICALS'
    WHEN ITMC.ITMCGCATEGNAME LIKE '%PHARMACY%' THEN 'PHARMACY'
    WHEN ITMC.ITMCGCATEGNAME LIKE '%LAB%' THEN 'LABORATORY'
      WHEN ITMC.ITMCGCATEGNAME LIKE '%OPERATION THEAT%' THEN 'OPERATION THEATRE'
--     ELSE  'OPERATION THEATRE'
    END AS 'top',
-- IF(ITM.ITEMTYPE = 'F','Opticals',(IF(ITM.ITEMTYPE = 'D','Pharmacy',IF(ITM.ITEMTYPE = 'M','Surgery & Others','Opticals')))) AS 'top',
-- IF(ITM.ITEMTYPE = 'F','Opticals',(IF(ITM.ITEMTYPE = 'D','Pharmacy',IF(ITM.ITEMTYPE = 'M','Surgery','Opticals')))) AS 'second',
ITM.ADITMDEPT AS 'second',
ITMC.ITMCGCATEGNAME AS 'group',
ITM.SUBCATEGORY AS 'sub_group',
BILL.BILL_NO AS 'bill_no',
-(RETURNDET.RETURNQUANTITY) AS 'quantity',
IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) AS 'unit_price',
IF(SSD.COST_PRICE IS NULL ,IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.COST_PRICE) AS 'cost_price',
-(IF(SSD.UNIT_PRICE IS NULL , IF(ITM.ADITMUNITRATE IS NULL,ITM.ADITMUNITRATE,ITM.ADITMUNITRATE) ,SSD.UNIT_PRICE) * (RETURNDET.RETURNQUANTITY))  AS 'actual_value',
RDT.TAX AS 'tax',
RDT.VALUE AS 'tax_percent',
UNIT.ACCOUNTUNIT AS 'branch',
ROC.DESCRIPTION AS 'entity',
IF(ITMC.ITMCGCATEGNAME = 'LENS','OPTICAL LENS',DEPT.DEPARTMENTNAME) AS 'unit',
SALES.WORKORDERSTATUS AS 'wo_status',
IF(MANF.ID IS NULL,ITM.MANUFACTURERID,MANF.MANUFACTURER) AS MANUFACTURER
FROM
RT_DATA_ACCOUNT_UNIT UNIT
JOIN BILL_PATIENT_BILL BILL ON BILL.ACC_UNIT_ID = UNIT.ID
JOIN RT_DATA_CORE RDC ON RDC.ID=UNIT.ID
JOIN RT_ORGANIZATION_CORE ROC ON ROC.ID=RDC.TENANTID
JOIN BILL_SERVICE_DETAIL DTL ON BILL.ID = DTL.BILL_ID
JOIN RT_TICKET_DIRECTSALES SALES ON DTL.SERVICE_ID = SALES.ID
JOIN RT_TICKET_DIRECTSALESDETAIL SDTL ON SALES.ID = SDTL.SALESID
JOIN `RT_TICKET_SALESRETURNDETAIL` RETURNDET ON RETURNDET.SALESDETAILID = SDTL.ID
JOIN RT_TICKET_CORE RETCORE ON RETCORE.ID = RETURNDET.ID
JOIN RT_DATA_ITEM ITM ON ITM.ID = SDTL.ITEMID LEFT JOIN  RT_ORGANIZATION_MANUFACTURER MANF ON MANF.ID = ITM.MANUFACTURERID
LEFT JOIN RT_DATA_TAX RDT ON RDT.ID=ITM.TAXTYPE
LEFT JOIN RT_INDIVIDUAL_PATIENT AS PAT ON(BILL.PATIENT_ID = PAT.ID)
JOIN RT_DATA_ITEM_CATEGORY ITMC ON ITM.CATEGORY = ITMC.ID
LEFT JOIN STORE_STOCK_DETAIL AS SSD ON (SDTL.STOCKDETAILID = SSD.ID)
LEFT JOIN RT_DATA_DEPARTMENT AS DEPT ON (SDTL.DEPTID = DEPT.ID)
WHERE
-- BILL.BILL_DATE BETWEEN concat(curdate(),' ','00:00:00') and concat(curdate(),' ','23:59:59')
DATE(RETCORE.CREATEDTIME)=DATE_SUB(CURDATE(), INTERVAL 1 DAY)
-- BETWEEN  '2018-04-01 00:00:00' AND '2019-05-15 23:59:59'
AND DTL.SERVICE_ID IS NOT NULL
-- AND (SALES.WORKORDERSTATUS = 'Goods Delivered' OR SALES.WORKORDERSTATUS IS NULL)
-- AND BILL.BILL_AMOUNT<>0
AND UNIT.ACCOUNTUNIT NOT IN ('ERC', 'OHC')
AND UNIT.DATASTATUS='Active'
-- AND ITM.ITEMTYPE<>'L'
-- and UNIT.ACCOUNTUNIT ='CMH'
) AS COG
WHERE top IS NOT NULL
