SELECT PARENT_BRANCH,BRANCH,PAYMENT_OR_REFUND_DATE,SUM(CASH_AMOUNT)+SUM(REFUND_CASH_AMOUNT)  AS CASH_AMOUNT,
SUM(CARD_AMOUNT)+SUM(CARD_SERVICE_CHARGE_AMOUNT)+SUM(REFUND_CARD_AMOUNT) AS CARD_AMOUNT,
SUM(CHEQUE_AMOUNT)+SUM(REFUND_CHEQUE_AMOUNT) AS CHEQUE_AMOUNT,
SUM(FUND_TRANSFER_AMOUNT) AS FUND_TRANSFER_AMOUNT,
SUM(PAYTM_AMOUNT) AS PAYTM_AMOUNT,SUM(DD_AMOUNT) AS DD_AMOUNT,
SUM(ONLINE_AMOUNT) AS ONLINE_AMOUNT FROM collection_detail
 WHERE PAYMENT_OR_REFUND_DATE = curdate()
 AND PARENT_BRANCH IN ('AEH','AHC','AHI')
  GROUP BY
BRANCH,
PAYMENT_OR_REFUND_DATE
