SELECT CONCAT(RIP.SALUTATION,'.',RIP.PATIENTNAME) AS PATNAME,CRE.GENDER

,RIP.PATIENTID,RIP.MOBILENO,DATE(CRE.DATEOFBIRTH) AS DOB,
RIP.AGE,RIP.REGISTEREDDATE FROM RT_INDIVIDUAL_PATIENT AS RIP
LEFT JOIN RT_INDIVIDUAL_CORE AS CRE ON RIP.ID=CRE.ID
INNER JOIN `RT_ORGANIZATION_CORE` AS ORG ON ORG.ID=CRE.TENANTID
WHERE ORG.ORGANIZATIONNAME ='VSH'
AND (MONTH(CRE.DATEOFBIRTH)= MONTH(?) AND DAY(CRE.DATEOFBIRTH)=DAY(?))
ORDER BY
CRE.DATEOFBIRTH ASC
