const modules = require('./modules')
const app = modules.express()

app.use(modules.cookie_parser())
app.use(modules.morgan('dev'))
app.use(modules.body_parser.urlencoded({ extended: false }))
app.use(modules.body_parser.json())
app.use(modules.cors())
app.use(modules.compression())
app.use(modules.helmet())
app.use(modules.session({ name: 'session_ID', secret: 'Bi$$DS@@J&a&i&*', resave: false, saveUninitialized: true, cookie: { maxAge: 60000 } }))

// modules.cron_job.schedule;

app.get('/api-super/:date', modules.routes.main_route)
app.get('/api-normal/:date/:name', modules.routes.test_route)
app.get('/api-revenue-super/:date', modules.routes.main_route_revenue)
app.get('/api-revenue-normal/:date/:name', modules.routes.test_route_revenue)
app.get('/api-branches/:entity/:region', modules.routes.branches)
app.get('/api-region/:entity', modules.routes.region)
app.get('/api-cogs-dashboard/:date/:entity/:region/:branch', modules.routes.monthlyData)
app.get('/api-super-ot/:date', modules.routes.main_ot)
app.get('/health', modules.routes.health)
app.post('/login', modules.routes.testLogin)
app.get('/logout', modules.routes.logout)
app.post('/api-changepassword', modules.routes.changePassword)
app.get('/api-newpod-super/:date', modules.routes.main_route_newopd)
app.get('/api-newpod-normal/:date/:name', modules.routes.main_route_newopd_normal)
app.get('/api-opticals-super/:date',modules.routes.opticals)
app.get('/api-discount-super/:frmdate/:todate/:department',modules.routes.discount)
app.get('/api-collection-super/:fromdate/:todate/:entity/:branch',modules.routes.collectiondetailim)
app.get('/api-branch/:entity', modules.routes.branch)
app.get('/api-usage-tracker/:date', modules.routes.main_route_usage_tracker)
app.get('/api-consultation-super/:date',modules.routes.consultation)
app.get('/api-chbranch/:name', modules.routes.ch_branch)
app.get('/api-chbills/:fromdate/:todate/:visit/:branch/:type/:name', modules.routes.chbills)
app.get('/api-drt', modules.routes.drt)
app.get('/api-drtdetail/:id', modules.routes.drtdetail)
app.post('/api-drtbills', modules.routes.drtbills)
app.get('/api-billdrt/:id', modules.routes.billdrt)
app.get('/api-schbranch/:name', modules.routes.sch_branch)
app.get('/api-schbills/:fromdate/:todate/:status/:branch/:name', modules.routes.schbills)
app.post('/api-schbillinsert',modules.routes.schbillinsert)
app.post('/api-schbillcancel',modules.routes.schbillcancel)
app.get('/api-finbranch', modules.routes.fin_branch)
app.get('/api-finbills/:fromdate/:todate/:status/:branch/:name', modules.routes.finbills)
app.post('/api-finbillinsert',modules.routes.finbillinsert)
app.post('/api-finbillcancel',modules.routes.finbillcancel)
app.listen(8888, () => console.log(`App listening on port 8888`))
