
SELECT t1.branch,SUM(t1.count)+SUM(t2.count) AS sum_count FROM 
(SELECT
	UNT.ACCOUNTUNIT AS branch
	,MONTH(CRE.`CREATEDTIME`) AS MONTH
	, COUNT(*) AS COUNT
FROM
	RT_INDIVIDUAL_PATIENT PAT 
	JOIN RT_INDIVIDUAL_CORE CRE
	ON CRE.ID=PAT.ID
	JOIN `RT_DATA_ACCOUNT_UNIT` UNT ON PAT.ACCUNIT = UNT.ID
	
WHERE
	DATE(CRE.`CREATEDTIME`) BETWEEN  ? AND ?
GROUP BY
	branch
	, MONTH(CRE.`CREATEDTIME`)) AS t1
INNER JOIN
(SELECT 
	UNT.ACCOUNTUNIT AS branch
	, MONTH(VISITDATE) AS MONTH
	, COUNT(*) AS COUNT
FROM
	RT_INDIVIDUAL_PATIENT PAT 
	JOIN RT_TICKET_VISIT ON RT_TICKET_VISIT.PATIENTID = PAT.ID 
		AND STR_TO_DATE(PAT.REGISTEREDDATE,'%d/%m/%Y') < DATE(VISITDATE)
	JOIN BILL_PATIENT_BILL BPB ON PAT.ID = BPB.PATIENT_ID  
		AND BPB.VISIT_ID = RT_TICKET_VISIT.ID
	JOIN `RT_DATA_ACCOUNT_UNIT` UNT 
		ON BPB.`ACC_UNIT_ID` = UNT.ID
	JOIN BILL_SERVICE_DETAIL BSD ON BSD.BILL_ID = BPB.ID
		AND SERVICE_ID IS NULL
	JOIN RT_DATA_CORE RDC ON RDC.ID = BSD.CHARGEDETAIL_ID
	JOIN RT_DATA_CHARGE RDH ON RDH.ID = RDC.PARENT_TICKET_ID
	LEFT JOIN `RT_DATA_PAYORTYPE` PAYOR ON PAYOR.ID = BPB.`PAYOR_TYPE_ID`
WHERE
	DATE(BPB.BILL_DATE) BETWEEN ? AND ?
	AND UPPER(RDH.CHARGE) LIKE '%CONSULTA%'
	AND BSD.BILL_STATUS != 2
	AND (
	 (PAYOR.`PAYORCATEGORY`='CASH' AND BPB.DUE_AMOUNT = 0)
	OR 
	(PAYOR.`PAYORCATEGORY` NOT IN ('CASH')
	OR 
	(BPB.`PAYOR_TYPE_ID` IS NULL)
	)
	)
GROUP BY branch
	, MONTH(VISITDATE)) AS t2
ON t1.branch = t2.branch
GROUP BY t1.branch,t2.branch,t1.month,t2.month