SELECT  BPB.ID AS 'bill_id',BPB.BILL_NO AS 'bill_no',BPB.TPA_CLAIM_ID AS 'tpa_claim',RIC.GENDER AS gender,TDAD.ADVICEDEYE AS eye
FROM BILL_PATIENT_BILL AS BPB
INNER JOIN RT_ORGANIZATION_CORE AS ROC ON ROC.ID=BPB.TENANTID
LEFT JOIN RT_INDIVIDUAL_CORE AS RIC ON RIC.ID=BPB.PATIENT_ID
LEFT JOIN  RT_TICKET_DOCTOR_ADVICE AS TDA ON BPB.ID=TDA.BILLID
LEFT JOIN RT_TICKET_CORE AS CRE ON TDA.ID=CRE.PARENT_TICKET_ID
LEFT JOIN RT_TICKET_DOCTOR_ADVICEDETAIL AS TDAD ON TDAD.ID=CRE.ID
WHERE DATE(REVENUE_DATE)=DATE_SUB(CURDATE(), INTERVAL 1 DAY) AND CLAIM_AMOUNT >0
AND ROC.DESCRIPTION IN('AHC','AEH','AHI')
ORDER BY
ROC.ORGANIZATIONNAME
