SELECT
  BPB.ID AS 'bill_id',BPB.BILL_NO AS 'bill_no',BPB.TPA_CLAIM_ID AS 'tpa_claim',
RIC.GENDER AS gender,IF(TDAD.ADVICEDEYE IS NULL,TDAD.ADVICEDEYE,CONCAT(UPPER(TDAD.ADVICEDEYE),' EYE')) AS eye,
DATE(BPB.REVENUE_DATE) AS add_date,
RIP.CONTACTADDRESS AS address,RDC.CHARGECODE AS 'code'
 FROM BILL_PATIENT_BILL AS BPB

LEFT JOIN RT_INDIVIDUAL_PATIENT AS RIP ON RIP.ID=BPB.PATIENT_ID
 INNER JOIN RT_ORGANIZATION_CORE AS ROC ON ROC.ID=BPB.TENANTID
 LEFT JOIN RT_INDIVIDUAL_CORE AS RIC ON RIC.ID=BPB.PATIENT_ID
 LEFT JOIN  RT_TICKET_DOCTOR_ADVICE AS TDA ON BPB.ID=TDA.BILLID
 LEFT JOIN RT_TICKET_CORE AS CRE ON TDA.ID=CRE.PARENT_TICKET_ID
 LEFT JOIN RT_TICKET_DOCTOR_ADVICEDETAIL AS TDAD ON TDAD.ID=CRE.ID
 LEFT JOIN RT_DATA_CHARGE AS RDC ON RDC.ID=TDAD.CHARGENAME
WHERE
 DATE(REVENUE_DATE)=DATE_SUB(CURDATE(), INTERVAL 1 DAY) AND CLAIM_AMOUNT >0
AND ROC.DESCRIPTION IN('AHC','AEH','AHI')
ORDER BY
ROC.ORGANIZATIONNAME,
BPB.BILL_NO
