SELECT
DIRECTISSUE.ISSUEID AS ISSUE_ID,
'' AS STNRETURN,
DIRECTISSUE.ISSUEDDATE,
ITEM.ADITMNAME AS ITEM_NAME,
DIRECTISSUEDETAIL.BATCHNO AS BATCH_NO,
DIRECTISSUEDETAIL.EXPIRYDATE,
DIRECTISSUEDETAIL.QUANTITY AS ISSUED_QUANTITY,
STOCKDETAIL.MRP AS MRP,
    STOCKDETAIL.COST_PRICE AS COSTPRICE,
    STOCKDETAIL.UNIT_PRICE AS UNITPRICE,
    DEPARTMENT.DEPARTMENTNAME AS ISSUING_DEPARTMENT,
DEPART.DEPARTMENTNAME AS RECEIVING_DEPARTMENT,
CORE.CREATEDBY AS USER_NAME,
ITEM.HSN_SAC
FROM
RT_TICKET_DIRECTISSUE AS DIRECTISSUE
LEFT JOIN RT_TICKET_DIRECTISSUEDETAIL  DIRECTISSUEDETAIL ON DIRECTISSUEDETAIL.ISSUEID=DIRECTISSUE.ID
LEFT JOIN RT_DATA_ITEM  ITEM ON ITEM.ID = DIRECTISSUEDETAIL.ITEMID
LEFT JOIN RT_TICKET_CORE CORE ON CORE.ID= DIRECTISSUE.ID
LEFT JOIN RT_DATA_DEPARTMENT DEPARTMENT ON DEPARTMENT.ID = DIRECTISSUE.ISSUINGDEPARTMENT
LEFT JOIN RT_DATA_DEPARTMENT DEPART ON DEPART.ID=DIRECTISSUE.RECEIVINGDEPARTMENT
INNER JOIN STORE_STOCK_DETAIL AS STOCKDETAIL ON STOCKDETAIL.ID = DIRECTISSUEDETAIL.STOCKDETAILID
LEFT JOIN RT_TICKET_ITEMREQUESTDETAIL AS ITEMREQDETAIL ON ITEMREQDETAIL.ID=DIRECTISSUEDETAIL.ITEMREQUESTDETAILID
LEFT JOIN RT_TICKET_ITEMREQUEST AS ITEMREQ ON ITEMREQ.ID=ITEMREQDETAIL.ITEMNAMEHIDDEN
WHERE
           DEPARTMENT.DEPARTMENTTYPE='Stock'
    AND DATE(DIRECTISSUE.ISSUEDDATE)=CURDATE()
  AND DIRECTISSUE.DEPENDENT !='ISSUERETURN'
 AND DIRECTISSUEDETAIL.QUANTITY >0

UNION

SELECT
DIRISSUE.ISSUEID AS ISSUE_ID,
DIRECTISSUE.RETURNNO AS RETURNNO,
DIRECTISSUE.RETURNDATE,
ITEM.ADITMNAME AS ITEM_NAME,
DIRECTISSUEDETAIL.BATCHNO AS BATCH_NO,
DIRECTISSUEDETAIL.EXPIRYDATE,
DIRECTISSUEDETAIL.RETURNQUANTITY AS ISSUED_QUANTITY,
STOCKDETAIL.MRP AS MRP,
    STOCKDETAIL.COST_PRICE AS COSTPRICE,
    STOCKDETAIL.UNIT_PRICE AS UNITPRICE,
    DEPARTMENT.DEPARTMENTNAME AS ISSUING_DEPARTMENT,
DEPART.DEPARTMENTNAME AS RECEIVING_DEPARTMENT,
CORE.CREATEDBY AS USER_NAME,
ITEM.HSN_SAC
FROM
RT_TICKET_ISSUERETURN AS DIRECTISSUE
JOIN `RT_TICKET_DIRECTISSUE` DIRISSUE ON DIRISSUE.ISSUEID = DIRECTISSUE.ISSUENO
JOIN `RT_TICKET_DIRECTISSUEDETAIL` DIRECTISSUEDETAIL ON DIRECTISSUEDETAIL.ISSUEID = DIRISSUE.ID
LEFT JOIN RT_DATA_ITEM  ITEM ON ITEM.ID = DIRECTISSUEDETAIL.ITEMID
LEFT JOIN RT_TICKET_CORE CORE ON CORE.ID= DIRECTISSUE.ID
LEFT JOIN RT_DATA_DEPARTMENT DEPARTMENT ON DEPARTMENT.ID = DIRISSUE.ISSUINGDEPARTMENT
LEFT JOIN RT_DATA_DEPARTMENT DEPART ON DEPART.ID=DIRISSUE.RECEIVINGDEPARTMENT
INNER JOIN STORE_STOCK_DETAIL AS STOCKDETAIL ON STOCKDETAIL.ID = DIRECTISSUEDETAIL.STOCKDETAILID
LEFT JOIN RT_TICKET_ITEMREQUESTDETAIL AS ITEMREQDETAIL ON ITEMREQDETAIL.ID=DIRECTISSUEDETAIL.ITEMREQUESTDETAILID
LEFT JOIN RT_TICKET_ITEMREQUEST AS ITEMREQ ON ITEMREQ.ID=ITEMREQDETAIL.ITEMNAMEHIDDEN
WHERE
           DEPARTMENT.DEPARTMENTTYPE='Stock'
     AND DATE(DIRECTISSUE.RETURNDATE)=CURDATE()
 AND DIRECTISSUEDETAIL.RETURNQUANTITY >0
