SELECT rd.TRANSACTION_DATE AS 'BILLEDDATE',rd.BILLED,rd.NATIVE,rd.AGENCY_NAME,rd.UNIT,rd.GROUP,rd.MRN,
rd.PATIENT_NAME,rd.VISIT_TYPE,rd.BILLNO
,SUM(TOTAL_AMOUNT) AS 'totalamount',SUM(DISCOUNT_AMOUNT) AS 'discount',SUM(NET_AMOUNT) AS 'netamount'
,SUM(PATIENT_AMOUNT) AS 'patamount',SUM(PAYOR_AMOUNT) AS 'tpaamount',DATE(rdt.send_date) AS 'senddate',
rdt.*
 FROM revenue_details AS rd
INNER JOIN revenue_detail_tpa AS rdt ON rdt.bill_id=rd.EXTERNAL_ID
 WHERE BILLED=? AND TRANSACTION_DATE BETWEEN ? AND ?
AND AGENCY_NAME NOT LIKE 'SELF PAYING'
GROUP BY
rd.MRN,
rd.BILLNO
ORDER BY
senddate ASC,
TRANSACTION_DATE DESC
